server:
  port: 8801

spring:
  application:
    name: homepage-auth
  profiles:
    active: dev
  web:
    resources:
      add-mappings: false

springdoc:
  api-docs:
    # 自定义API文档的JSON/YAML端点路径，默认为 /v3/api-docs
    path: /api-docs
  swagger-ui:
    # 自定义Swagger UI界面的访问路径，默认为 /swagger-ui/index.html
    path: /swagger-ui.html