server:
  port: 8801

spring:
  application:
    name: homepage-auth
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/homepage?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root # 测试环境用户名
    password: 123 # 测试环境密码
  web:
    resources:
      add-mappings: false

springdoc:
  api-docs:
    # 自定义API文档的JSON/YAML端点路径，默认为 /v3/api-docs
    path: /api-docs
  swagger-ui:
    # 自定义Swagger UI界面的访问路径，默认为 /swagger-ui/index.html
    path: /swagger-ui.html

# 初始化管理员账号密码
app:
  admin:
    init-account: admin
    init-password: password